# REPOSITORIES
tap 'caskroom/cask'
tap 'homebrew/science'
tap 'homebrew/python'  # for numpy

# SHELL
brew 'zsh'
brew 'ack'
brew 'tldr'
brew 'antigen'
brew 'thefuck'
brew 'ccat'
brew 'htop'

# PROGRAMMING & UTILITY
#mas 'Xcode', id: 497799835 # Will be done manually
brew 'cmake'
brew 'ctags'
brew 'git'
brew 'macvim', args: ['with-override-system-vim', 'with-python3']
brew 'opencv3', args: ['HEAD', 'with-contrib', 'with-python3', 'with-ffmpeg']
brew 'pandoc'
brew 'pandoc-citeproc'
brew 'python3'
brew 'ruby'
cask 'java'
cask 'mactex'
cask 'miniconda'
cask 'rstudio'

# PRODUCTIVITY
cask 'filezilla'
cask 'google-chrome'
cask 'libreoffice'
cask 'splitshow'

# OTHER
brew 'gpg'
cask 'amethyst'
cask 'caffeine'
cask 'discord'
cask 'keybase'
cask 'skype'
cask 'steam'
cask 'telegram-desktop'

# Dependencies (just dumped)
brew 'cairo'
brew 'cask'
brew 'cscope'
brew 'dirmngr'
brew 'eigen'
brew 'emacs'
brew 'ffmpeg'
brew 'fontconfig'
brew 'freetype'
brew 'gcc'
brew 'gdbm'
brew 'gettext'
brew 'glib'
brew 'gmp'
brew 'gpg-agent'
brew 'homebrew/science/r'
brew 'icu4c'
brew 'ilmbase'
brew 'isl'
brew 'jpeg'
brew 'lame'
brew 'libassuan'
brew 'libffi'
brew 'libgcrypt'
brew 'libgpg-error'
brew 'libksba'
brew 'libmpc'
brew 'libpng'
brew 'libtiff'
brew 'libusb'
brew 'libusb-compat'
brew 'mas'
brew 'mercurial'
brew 'mpfr'
brew 'numpy'
brew 'openexr'
brew 'openssl'
brew 'pcre'
brew 'pinentry'
brew 'pixman'
brew 'pkg-config'
brew 'pth'
brew 'python'
brew 'readline'
brew 'sqlite'
brew 'x264'
brew 'xvid'
brew 'xz'
